### ISSUE TITLE
Prosba o dopisanie sie do pliku README.md

### ISSUE THREAD

**Issue by Serp-ent** [Serp-ent/zesp11#1]
Każdy członek zespołu, powinien samemu dopisać się do pliku 'README.md'
za pomocą pull request'a z nowego branch'a
>[!IMPORTANT]
> Wiadomości commit'ów powinny być w języku angielskim

Aby się dopisać, utwórz nowy branch na którym się dopiszesz, następnie wykonaj 'pull request' na branch '1-prosba-o-dopisanie-sie-do-pliku-readmemd'.

##### Krok po kroku
1. Przejdź na branch '1-prosba-o-dopisanie-sie-do-pliku-readmemd' związany z tym wątkiem.
2. Edytuj plik README.md -> dopisz się do niego.
>[!WARNING]
> Wykonaj pull request na ten branch  (NIE NA MAIN)

Dodane branch'e usunę kiedy wszyscy się zapiszą.

**Comment by Erdahil** [comment]
test comment
